services:
  msgx10-diffusers:
    image: gx10-diffusers:v1
    container_name: diffusers
    env_file:
      - ../../.env
    shm_size: '64gb'
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    environment:
      - HF_TOKEN=${HF_TOKEN}
      # Optimierung für PyTorch & Blackwell
      - TORCH_CUDNN_V8_API_ENABLED=1
      - CUDA_MODULE_LOADING=LAZY
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - ${HF_HOME}:/root/.cache/huggingface
      - /mnt/gx10_ext1/models:/root/models
      - /home/dirk/docker/dgx-spark-stack/ki-services/diffusers/app:/app
    working_dir: /app
    command: uvicorn ${DIFFUSERS_MODULE:-main-Flux1}:app --host 0.0.0.0 --port ${DIFFUSERS_PORT:-8889}
