services:
  controller:
    build:
      context: ../..
      dockerfile: control-plane/controller/Dockerfile
    env_file:
      - ../../.env
    image: controller-base:v1.2
    container_name: controller
    command: tail -f /dev/null

    # Aktiviert das interaktive Terminal (entspricht -it bei docker run)
    tty: true
    stdin_open: true
#    ports:
#      - "8501:8501"  # Streamlit
#      - "8888:8888"  # JupyterLab / VS Code Server
    volumes:
      # nur bei control planes wird der gesamte Workspace des Repos gemountet
      - ../..:/workspace
      # controller root directory
      - .:/app
      # code of basic applications, common libs and configs from dgx-spark-stack monorepo
      - ../../applications:/spark/applications
      - ../../libs:/spark/libs
      - ../../configs:/spark/configs
      # projects dir contains data, logs and configs
      - ../../projects:/spark/projects
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app:/app/src:/spark/libs:/spark/configs:/spark/applications



