---
compose_bake: "true"
container_uid: 1000
container_gid: 1000

microservice_config_path: "/spark/configs/microservices.yaml"
dispatcher_ip: "100.86.238.115"

redis_host: "100.86.238.115"
redis_port: 6379

hf_home: "/mnt/gx10_ext1/models/huggingface_cache"
models_extssd: "/mnt/gx10_ext1/models"

s3_endpoint_ip: "100.86.238.115"
s3_bucket_name: "my-rag-bucket"

# GUI Defaults
gui_dev_command: "python /spark/applications/rag_gui/start_gui.py"

app_db_module: "rag_gui.core.sqlite_repository"
app_db_class: "SQLiteRepository"
app_db_path: "/spark/applications/rag_gui/dev_state.db"
app_reset_db: "false"

app_orchestrator_module: "rag_gui.core.orchestrator"
app_orchestrator_class: "Orchestrator"

chainlit_presenter_module: "rag_gui.chainlit.presenter"
chainlit_presenter_class: "ChainlitPresenter"

nicegui_presenter_module: "rag_gui.nicegui.presenter"
nicegui_presenter_class: "NiceGUICockpitPresenter"

app_bus_module: "rag_gui.core.redis_bus"
app_bus_class: "RedisEventBus"
