services:
  vllm-nvfp4:
    env_file:
      - ../../.env
    image: avarok/dgx-vllm-nvfp4-kernel:v22
    container_name: vllm-nvfp4
    restart: always
    network_mode: host
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]    
    volumes:
      - ${HF_HOME}:/root/.cache/huggingface
      - ${MODELS_EXTSSD}:/root/models
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - VLLM_USE_FLASHINFER_MOE_FP4=0
      - VLLM_TEST_FORCE_FP8_MARLIN=1
      - VLLM_NVFP4_GEMM_BACKEND=marlin
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
      - MODEL=${MODEL}
      - PORT=8888
      - GPU_MEMORY_UTIL=${GPU_MEMORY_UTIL}
      - MAX_MODEL_LEN=${MAX_MODEL_LEN}
      - MAX_NUM_SEQS=128
      - VLLM_EXTRA_ARGS=--attention-backend flashinfer --kv-cache-dtype fp8
      # Isoliert den Start auf GPU von vllm von den anderen Containern
      - NCCL_SOCKET_IFNAME=lo
      - GLOO_SOCKET_IFNAME=lo
    command: serve



