---
- name: Deploy DGX Spark Stack
  hosts: localhost
  connection: local
  vars_files:
    - vars/ryzon9.yaml
    - vars/secrets_ryzon9.yaml

  vars:
    # Verwende 'default', falls keine Variable (present / absent) übergeben wird
    deployment_action: "{{ target_state | default('present') }}"

  tasks:
    - name: 1. Generate central .env file from template
      template:
        src: templates/env.j2
        dest: "{{ playbook_dir }}/../.env"
        mode: '0644'

    - name: 2. Manage Dispatcher Service
      community.docker.docker_compose_v2:
        project_src: "{{ playbook_dir }}/../microservices/dispatcher"
        env_files:
          - "{{ playbook_dir }}/../.env"
        state: "{{ deployment_action }}"
      tags: [dispatcher]

    - name: 3. Manage Garage S3 Service
      community.docker.docker_compose_v2:
        project_src: "{{ playbook_dir }}/../microservices/garage-s3"
        env_files:
          - "{{ playbook_dir }}/../.env"
        state: "{{ deployment_action }}"
      tags: [garage]

    - name: 4. Manage Pipeline-Server Service
      community.docker.docker_compose_v2:
        project_src: "{{ playbook_dir }}/../microservices/pipeline-server"
        env_files:
          - "{{ playbook_dir }}/../.env"
        state: "{{ deployment_action }}"
      tags: [pipeline-server]

    - name: 5. Manage Qdrant Vector Database
      community.docker.docker_compose_v2:
        project_src: "{{ playbook_dir }}/../microservices/qdrant"
        env_files:
          - "{{ playbook_dir }}/../.env"
        state: "{{ deployment_action }}"
      tags: [qdrant]

    - name: 6. Manage Redis Database
      community.docker.docker_compose_v2:
        project_src: "{{ playbook_dir }}/../microservices/redis"
        env_files:
          - "{{ playbook_dir }}/../.env"
        state: "{{ deployment_action }}"
      tags: [redis]

    - name: 7. Manage Control Plane gui_dev for Chainlit / NiceGUI
      community.docker.docker_compose_v2:
        project_src: "{{ playbook_dir }}/../control-plane/gui_dev"
        env_files:
          - "{{ playbook_dir }}/../.env"
        state: "{{ deployment_action }}"
      tags: [gui_dev]
