[local_machines]
acer ansible_connection=local host_var_prefix=acer
ryzon9 ansible_connection=local host_var_prefix=ryzon9

[gx10_host]
gx10 ansible_host=100.117.200.75 ansible_user=dirk host_var_prefix=gx10
