services:
  infinity:
    build: .
    env_file:
      - ../../.env
    image: gx10-infinity:v1
    container_name: infinity
    restart: always
    volumes:
      - ${HF_HOME}:/app/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    ports:
      - "7997:7997"
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - HF_HOME=/app/.cache
      - INFINITY_MODEL_ID=BAAI/bge-m3
      - INFINITY_BATCH_SIZE=32
    command:
    - v2
    - --model-id
    - BAAI/bge-m3
    - --model-id
    - BAAI/bge-reranker-v2-m3 
    - --port
    - "7997"
    - --device
    - cuda
    - --engine
    - torch
    - --dtype
    - float16
    - --batch-size
    - "32"
    - --model-warmup


